apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-pod1
  name: new-pod1-lab16
  namespace: demo-lab16
spec:
  containers:
  - image: nginx
    name: new-pod1


---
apiVersion: v1
kind: Service
metadata:
  name: rest-simpleapp-svc-lab16
  namespace: demo-lab16
spec:
  type: LoadBalancer
  selector:
    run: new-pod1
  ports:
    - port: 8088
      targetPort: 80 
